### ISSUE TITLE
Cart tab not closing on removal of product

### ISSUE THREAD

**Issue by dare-devil-arrives** [jameskoster/woocommerce-cart-tab#51]
When I empty the cart content from the cart tab, cart tab is not closing like it used to do earlier.

WooCommerce 3.4.1, Storefront 2.3.1, WordPress 4.9.6

Can this be fixed? @jameskoster

**Comment by jameskoster** [comment]
Can you share a URL? I'm not seeing this issue.

**Comment by akash-dhawade** [comment]
@jameskoster 

I am facing the same issue. Have you tried reproducing it with only latest version of WooCommerce and Storefront active?

**Comment by jameskoster** [comment]
Maybe the issue needs to be explained a bit better, when I empty the cart I'm able to close the tab just fine?

**Comment by dare-devil-arrives** [comment]
Apologies for not being clear enough.

When a product is removed from the cart tab,
Till WC 3.1.2, the cart tab used to get auto closed if no product is in the cart.
From WC 3.2.0+, the cart tab does not get auto closed if no product is in the cart.

I can send you video if that helps.

Can this be fixed?

**Comment by akash-dhawade** [comment]
@jameskoster 

Any update on the issue? 

From WC 3.2.0+, mini cart uses AJAX for restoring and removing an item from the mini-cart because of which I guess the Cart tab does not closes automatically when all the items are removed. Please see the attached screenshot

1. With item in cart
![with-item-in-cart](https://user-images.githubusercontent.com/25526772/42163266-7a7efbb0-7e1f-11e8-8c75-5eb327f64da4.png)

2. No items in cart
![no-items-in-cart](https://user-images.githubusercontent.com/25526772/42163272-8129dd4a-7e1f-11e8-88ca-78164ed7efd4.png)

Can you please fix this!

**Comment by jameskoster** [comment]
Fixed in https://github.com/jameskoster/woocommerce-cart-tab/commit/875a4f6b142730c3959e30d86a399eb2818d53db

**Comment by mansi-shah-2248** [comment]
Thank you :+1:
